### ISSUE TITLE
How to get a local SIM card

### ISSUE THREAD

**Issue by dimaqq** [pythonsingapore/pycon-apac-2018#2]
At the airport:
* exchange (some) money to S$ or withdraw from an ATM
* recommended stalls, prices

In the city, best offers:
* Sim Lim center / little India prices
* Orchard prices
* On the periphery (if possible)

**Comment by sfdye** [comment]
- buy from https://www.changirecommends.com/ and collect at the airport

**Comment by mbrochh** [comment]
Done!
