### ISSUE TITLE
SSL cert is invalid

### ISSUE THREAD

**Issue by sfdye** [pythonsingapore/pycon-apac-2018#7]
![image](https://user-images.githubusercontent.com/1016390/35569669-b2c6c1be-0607-11e8-9f9d-0fb8cd8753df.png)
![image](https://user-images.githubusercontent.com/1016390/35569713-d2c91dfe-0607-11e8-9e5c-ae11e7e029f3.png)

**Comment by mbrochh** [comment]
@sfdye we moved the hosting to github pages, which does not support HTTPS for custom domains. Your browser still has the URL cached and it automatically redirects you to the HTTPS version.

You need to delete cached files for that domain and then visit http://pycon.sg

I will try and see if I can get a workaround with Cloudfare going, there seem to be ways to get HTTPS support by putting Cloudfare in front of Github Pages.

**Comment by sfdye** [comment]
Just FYI, I am hosting my personal github pages on netlify and it worked really well. Free SSL certificate too. Took me less 10 mins to set up.

________________________________

**Comment by sfdye** [comment]
Seems to be fixed now.

**Comment by mbrochh** [comment]
@sfdye I moved the hosting to netlify last night as well and now we have proper HTTPS again! Thank you so much for the tip!

**Comment by sfdye** [comment]
@mbrochh Awesome! See you tomorrow at the meet-up.
